### ISSUE TITLE
NPE in TypeImpl with anonymous inner classes - getSimpleName returns ""

### ISSUE THREAD

**Issue by astubbs** [forge/roaster#202]
```
java.lang.NullPointerException: Cannot invoke "org.jboss.forge.roaster._shade.org.eclipse.jdt.core.dom.Type.toString()" because "this.type" is null
	at org.jboss.forge.roaster.model.impl.TypeImpl.getQualifiedName(TypeImpl.java:178)
	at org.jboss.forge.roaster.model.impl.JavaSourceImpl.addImport(JavaSourceImpl.java:285)
	at org.jboss.forge.roaster.model.impl.FieldImpl.setType(FieldImpl.java:341)
	at org.jboss.forge.roaster.model.impl.FieldImpl.setType(FieldImpl.java:327)
	at com.google.common.truth.extension.generator.TruthGenerator.addActualField(TruthGenerator.java:382)
```

getSimpleName():
> Returns the simple name of the underlying class as given in the source code. Returns an empty string if the underlying class is anonymous.

**Comment by gastaldi** [comment]
Can you provide a test case reproducing this bug?

**Comment by gastaldi** [comment]
@astubbs how do I reproduce that error?

**Comment by gastaldi** [comment]
I'll close it for now. Please reopen when you have a small reproducer. Thank you! 😉
