### ISSUE TITLE
cannot generate record source ?

### ISSUE THREAD

**Issue by maxandersen** [forge/roaster#238]
```
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS org.jboss.forge.roaster:roaster-api:RELEASE
//DEPS org.jboss.forge.roaster:roaster-jdt:RELEASE
//JAVA 17

import org.jboss.forge.roaster.Roaster;
import org.jboss.forge.roaster.model.source.JavaRecordSource;

public class j2son2java {

    public static void main(String... args) {

        final JavaRecordSource javaClass = Roaster.create(JavaRecordSource.class);
        javaClass.setDefaultPackage();
        javaClass.addAnnotation();

    }
}
```

gives me:

```
Exception in thread "main" org.jboss.forge.roaster.ParserException: Cannot find JavaParserProvider capable of producing JavaSource of type JavaRecordSource
	at org.jboss.forge.roaster.Roaster.create(Roaster.java:103)
	at j2son2java.main(j2son2java.java:13)
Caused by: java.lang.IllegalArgumentException: org.jboss.forge.roaster.model.source.JavaRecordSource
	... 2 more
```

what is needed to generate Records ?

also seem that JavaRecordSource has no way to set/define fields/properties to have in a record?

**Comment by gastaldi** [comment]
Ah looks like the support for records isn't fully implemented. Here is an example on how it works now: 

https://github.com/forge/roaster/blob/master/tests/src/test/java/org/jboss/forge/test/roaster/model/JavaRecordTest.java#L15-L19


I'll have a look at this
